// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace App_Teste.Models
{
    public partial class DependentesAgrupadosResult
    {
        public int? QTD { get; set; }
        public string Genero_Dependente { get; set; }
        public int? Ano_Nascimento { get; set; }
    }
}
