// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App_Teste.Models;

[Keyless]
public partial class VdependentesEfuncionario
{
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataNascimento { get; set; }

    public int? FuncionarioId { get; set; }

    [Column("GeneroID")]
    public int? GeneroId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string NomeGenero { get; set; }

    [Column("Nome_Funcionario")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeFuncionario { get; set; }

    [Column("Nascimento_Funcionario", TypeName = "datetime")]
    public DateTime? NascimentoFuncionario { get; set; }

    [Column("GeneroID_Funcionario")]
    public int? GeneroIdFuncionario { get; set; }

    [Column("Genero_Funcionario")]
    [StringLength(10)]
    [Unicode(false)]
    public string GeneroFuncionario { get; set; }
}