// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App_Teste.Models;

[Keyless]
public partial class VfuncionariosEdependente
{
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataNascimento { get; set; }

    public double Salario { get; set; }

    [Column("GeneroID")]
    public int? GeneroId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string NomeGenero { get; set; }

    [Required]
    [Column("Nome_Dependente")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeDependente { get; set; }

    [Column("Nascimento_Dependente", TypeName = "datetime")]
    public DateTime NascimentoDependente { get; set; }

    [Column("GeneroID_Dependente")]
    public int? GeneroIdDependente { get; set; }

    [Column("Genero_Dependente")]
    [StringLength(10)]
    [Unicode(false)]
    public string GeneroDependente { get; set; }
}