// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using App_Teste.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace App_Teste.Data
{
    public partial interface ITestePraticoContextProcedures
    {
        Task<int> AddDependentesTBAsync(string Nome, DateTime? DataNacimento, int? FuncionarioId, int? GeneroID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AddFuncionarioTBAsync(string Nome, DateTime? DataNacimento, double? Salario, int? GeneroID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AtualizaDependentesTBAsync(int? ID, string Nome, DateTime? DataNacimento, int? GeneroID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AtualizaFuncionarioTBAsync(int? ID, string Nome, DateTime? DataNacimento, double? Salario, int? GeneroID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<BuscaDependentesTBResult>> BuscaDependentesTBAsync(string Nome, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<BuscaFuncionarioTBResult>> BuscaFuncionarioTBAsync(string Nome, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<BuscaIDDependentesTBResult>> BuscaIDDependentesTBAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<BuscaIDFuncionarioTBResult>> BuscaIDFuncionarioTBAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteDependentesTBAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteFuncionarioTBAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DependentesAgrupadosResult>> DependentesAgrupadosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SelectDependentesTBResult>> SelectDependentesTBAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SelectFuncionarioTBResult>> SelectFuncionarioTBAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
