// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using App_Teste.Models;
using Microsoft.EntityFrameworkCore;

namespace App_Teste.Data;

public partial class TestePraticoContext : DbContext
{
    public TestePraticoContext(DbContextOptions<TestePraticoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<VdependentesEfuncionario> VdependentesEfuncionarios { get; set; }

    public virtual DbSet<Vfuncionario> Vfuncionarios { get; set; }

    public virtual DbSet<VfuncionariosEdependente> VfuncionariosEdependentes { get; set; }

    public virtual DbSet<VfuncionariosFiltroGenero> VfuncionariosFiltroGeneros { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<VdependentesEfuncionario>(entity =>
        {
            entity.ToView("VDependentesEFuncionarios");
        });

        modelBuilder.Entity<Vfuncionario>(entity =>
        {
            entity.ToView("VFuncionarios");
        });

        modelBuilder.Entity<VfuncionariosEdependente>(entity =>
        {
            entity.ToView("VFuncionariosEDependentes");
        });

        modelBuilder.Entity<VfuncionariosFiltroGenero>(entity =>
        {
            entity.ToView("VFuncionariosFiltroGenero");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}