name: .NET Build CI HOMOLOGAÇÃO

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: well_self_host

    env:
      Solution_Name: App_Teste.sln
      Backup_Root_Dir: C:\backup_publish
      Publish_Dir: C:\AppCRUD

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Create a backup
      id: create_backup
      run: |
        $timestamp = Get-Date -Format "yyyyMMddHHmmss"
        $solutionName = $env:Solution_Name -replace '\.sln$', ''
        $backupDir = "$env:Backup_Root_Dir\$solutionName\$timestamp"
        if (-not (Test-Path -Path $backupDir)) {
          New-Item -ItemType Directory -Force -Path $backupDir
        }
        $backupFileName = "backup_$timestamp.zip"
        Compress-Archive -Path $env:Publish_Dir\* -DestinationPath "$backupDir/$backupFileName"
        echo "backup_dir=$backupDir" >> $GITHUB_OUTPUT
      shell: powershell

    - name: Find App_Teste .csproj file
      id: find_csproj
      run: |
        $csproj = Get-ChildItem -Path . -Recurse -Filter App_Teste*.csproj | Select-Object -First 1
        if ($csproj) {
          Write-Host "Found App_Teste .csproj file: $($csproj.FullName)"
          echo "csproj_path=$($csproj.FullName)" >> $env:GITHUB_ENV
        } else {
          Write-Host "No App_Teste .csproj file found."
          exit 1
        }
        Write-Host "Project found: $($csproj.FullName)"
      shell: powershell

    - name: Ignore DBAppCRUD .csproj file
      run: |
        Get-ChildItem -Path . -Recurse -Filter DBAppCRUD*.csproj | ForEach-Object {
          Write-Host "Ignoring project: $($_.FullName)"
          Remove-Item $_.FullName -Force
        }
      shell: powershell

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: |
        if (Test-Path -Path $env:csproj_path) {
          dotnet restore $env:csproj_path
        } else {
          Write-Host "csproj_path is null or empty."
        }
      shell: powershell

    - name: Build App_Teste
      run: |
        if (Test-Path -Path $env:csproj_path) {
          dotnet build $env:csproj_path --configuration Release --no-restore
        } else {
          Write-Host "csproj_path is null or empty."
        }
      shell: powershell

    - name: Test App_Teste
      run: |
        if (Test-Path -Path $env:csproj_path) {
          dotnet test $env:csproj_path --no-build --verbosity normal
        } else {
          Write-Host "csproj_path is null or empty."
        }
      shell: powershell

    - name: Publish App_Teste
      run: |
        if (Test-Path -Path $env:csproj_path) {
          if (-not (Test-Path -Path $env:Publish_Dir)) {
            New-Item -ItemType Directory -Force -Path $env:Publish_Dir
          }
          msbuild $env:csproj_path /p:Configuration=Release /p:OutputPath=$env:Publish_Dir
        } else {
          Write-Host "csproj_path is null or empty."
        }
      shell: powershell

    - name: Upload backup artifact
      uses: actions/upload-artifact@v3
      with:
        name: Backup
        path: ${{ steps.create_backup.outputs.backup_dir }}/*.zip

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Published App
        path: ${{ env.Publish_Dir }}
